#!/usr/bin/env python3
# power-profiles-hooks - minimal, no logging

import os
import dbus

from gi.repository import GLib
from dbus.mainloop.glib import DBusGMainLoop

SENDER      = "net.hadess.PowerProfiles"
OBJECT      = "/net/hadess/PowerProfiles"
IFACE_PPD   = "net.hadess.PowerProfiles"
IFACE_PROPS = "org.freedesktop.DBus.Properties"

PREFIXES = ["/etc", "/usr/local/etc"]

oldprof = ""


def runhooks(prof: str) -> None:
    for pr in PREFIXES:
        d = f"{pr}/power-profiles.d/{prof}"
        if not os.path.isdir(d):
            continue

        for hk in sorted(os.listdir(d)):
            path = os.path.join(d, hk)
            if os.access(path, os.X_OK):
                os.system(path)


def on_properties_changed(iface_name, changed, invalidated):
    global oldprof

    if iface_name != IFACE_PPD:
        return

    if "ActiveProfile" in changed:
        newprof = str(changed["ActiveProfile"])
        runhooks(newprof)
        oldprof = newprof


def main() -> None:
    global oldprof

    DBusGMainLoop(set_as_default=True)
    bus = dbus.SystemBus()

    obj = bus.get_object(SENDER, OBJECT)
    props = dbus.Interface(obj, IFACE_PROPS)

    oldprof = str(props.Get(IFACE_PPD, "ActiveProfile"))
    runhooks(oldprof)

    bus.add_signal_receiver(
        on_properties_changed,
        signal_name="PropertiesChanged",
        dbus_interface=IFACE_PROPS,
        path=OBJECT,
        bus_name=SENDER,
        arg0=IFACE_PPD,
    )

    GLib.MainLoop().run()


if __name__ == "__main__":
    main()
